openapi: 3.0.3
info:
  title: Project specification
  version: '0.1'
  description: |-
    Project description.
paths:
  /status:
    get:
      summary: Get the project status
      responses:
        '200':
          description: The project health status.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    default: 'ok'
                    description: Contains only "ok".
                    example: 'ok'
                  php:
                    type: object
                    description: 'PHP engine stats.'
                    properties:
                      ver:
                        type: string
                        description: 'PHP version'
                        example: '8.2.4'
                      time:
                        type: number
                        description: Request execution time in seconds.
                        example: 0.308683
                      memory:
                        type: string
                        description: A formatted string of the request used memory (in kilobytes).
                        example: "361,904"
                  disk:
                    type: object
                    description: 'System disk status'
                    properties:
                      total:
                        type: string
                        description: Disk total size, in MB
                        example: '1,031,019'
                      free:
                        type: string
                        description: Disk free space, in MB
                        example: '948,392'
                      used:
                        type: string
                        description: Disk used space, in MB
                        example: '82,627'
                      used_%:
                        type: integer
                        description: Disk used space percentage
                        example: '9'
                  cpu_load:
                    type: array
                    description: CPU average load for 1, 5 and 15 minutes.
                    items:
                      type: number
                    minItems: 3
                    maxItems: 3
